### ISSUE TITLE
Password reset for user in Django admin broken

### ISSUE THREAD

**Issue by mraak** [howtographql/graphql-python#1]
Excellent tutorial btw.

I enabled users admin in Django admin quickly, like so:

users/admin.py
```
from django.contrib import admin
from .models import User
admin.site.register(User)
```

But now password is simply displayed as hash. there is no option anymore of resetting it. Any idea how to get that back?

**Comment by jonatasbaldin** [comment]
Hi there, sorry for the delay, didn't get a notification :(

Yes, there's a way to get it back, just change your code to this:
```
from django.contrib import admin
from django.contrib.auth.admin import UserAdmin

from .models import User


admin.site.register(User, UserAdmin)
```

Source: https://docs.djangoproject.com/en/2.0/topics/auth/customizing/#using-a-custom-user-model-when-starting-a-project

Does this solve your issue?

Thanks
