### ISSUE TITLE
Sync backend tutorial with frontend ones

### ISSUE THREAD

**Issue by ghost** [howtographql/graphql-python#5]
Thanks for this really well done tutorial. I really like the way howtographql site is constructed, however I thought that backend tutorials was in sync with frontend ones.

And when I started the react appolo tutorial with my python backend I discovered that I needed to make some changes to my django app. For example change port with to run graphql server on port 4000 and enable cors for the client app running on port 3000 with django-cors-header. 

Maybe this could be implemented with unitests run on every backend tutorial.

**Comment by jonatasbaldin** [comment]
Hello @benjaminabel!

For now, the objective is not to sync frontend and backend tutorials, since different developers write them.

I'll talk to the writers if we can accomplish something like this in the future.

But thanks for reaching out!

**Comment by ghost** [comment]
@jonatasbaldin thanks for your answer and this great tutorial.
