### ISSUE TITLE
I am having problem my query does not return data but in documentation everything is look fine 

### ISSUE THREAD

**Issue by reaganscofield** [howtographql/graphql-python#6]
when i query it, its return null
query
```graphql
query{
	products{
		id
		title
		timestamp
		image
	}
}
````
response
```graphql
{
	"data": {
		"products": null
	}
}
```

````python
import graphene
from graphene_django import DjangoObjectType

#my model
from .models import Products

class ProductTypes(DjangoObjectType):
    class Meta:
        model = Products


class QueryProducts(graphene.ObjectType):
    products =  graphene.List(ProductTypes)


    def resolveProducts(self, info):
        return Products.objects.all()
````

in database i have data but i don't why it does not query it, it does not even show error messagfe in the terminal the http response comes like:  [02/Jul/2018 15:06:37] "POST /graphql/? HTTP/1.1" 200 26

**Comment by jonatasbaldin** [comment]
Hello there! Is this related to the How to GraphQL tutorial? Because it seems you are using different models – something related to `Products`.

It it's not, I'll be glad to help you outside of this repo, you can find me on Twitter @jonatasbaldin or send me an email at jonatas dot baldin at gmail dot com.

Cheers!

**Comment by reaganscofield** [comment]
@jonatasbaldin  i solve my problem long times ago 

```
class QueryProducts(graphene.ObjectType):
    products =  graphene.List(ProductTypes)


    def resolve_products(self, info):
        return Products.objects.all()
```

**Comment by jonatasbaldin** [comment]
Alright, nice!
