### ISSUE TITLE
migration issue : posted_by' is an invalid keyword argument for this function 

### ISSUE THREAD

**Issue by swenremake** [howtographql/graphql-python#7]
I've  tried  everything i can think of but nothing working

Insomnia
`mutation {
  createLink(url: "https://github.com/jonatasbaldin",description:"jonatas'github") {
    id
    url
    description
    postedBy {
      id
      username
      email
    }
  }
}`

returns
`{
  "errors": [
    {
      "message": "'posted_by' is an invalid keyword argument for this function",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "createLink"
      ]
    }
  ],
  "data": {
    "createLink": null
  }
}`

**Comment by BenBera** [comment]
am facing the same issue can someone show me the solution
